### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by NoxiousPluK** [jaapio/dotfiles#1]
Hey Jaap,

Ik browste de PolderKnowledge website en kwam zo hier uit ;)

Mogelijk wil je wat files uit deze repo deleten en/of 'm hiden? O.a. je weechat config staat er open op, incl. passwords / passphrases.

Groetjes aan Mark!

**Comment by jaapio** [comment]
Jow,

Als er mensen zijn die mijn weechat pass willen hebben gaan ze vooral hun gang. Zowel de passphrases als de gebruikte wachtwoorden zijn niet erg boeiend. 

Maar dank voor de hit.
